FROM nvidia/cuda:10.0-base-ubuntu18.04

LABEL maintainer "BMW Group"


# The commands below install Cuda and libcudnn in order for the code to run on the GPU
ENV CUDNN_VERSION 7.4.2.24
LABEL com.nvidia.cudnn.version="${CUDNN_VERSION}"


RUN apt-get update && apt-get install -y --no-install-recommends \
  libcudnn7=$CUDNN_VERSION-1+cuda10.0 && \
  apt-mark hold libcudnn7 && \
  rm -rf /var/lib/apt/lists/*

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
	    vim \
	    nano \
        git \
        wget \
        ssh \
	    cuda-command-line-tools-10-0 \
        cuda-cublas-10-0 \
        cuda-cufft-10-0 \
        cuda-curand-10-0 \
        cuda-cusolver-10-0 \
        cuda-cusparse-10-0 \
        locales \
        python3 \
        python3-pip \
        wget \
        pkg-config\
        curl\
        docker.io 

RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py && \
    rm get-pip.py


RUN apt-get install -y python3-dev

RUN pip3 install docker GPUtil fastapi[all]==0.63.0

RUN pip3 install pydantic==1.7

# Set the locale (required for uvicorn)
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
  dpkg-reconfigure --frontend=noninteractive locales && \
  update-locale LANG=en_US.UTF-8
ENV LANG en_US.UTF-8 

COPY ./api /api

WORKDIR /api

CMD uvicorn main:app --host 0.0.0.0  --port 2222
