FROM tensorflow/tensorflow:2.5.0

COPY docker/requirements.txt .

COPY src/main /main


# Install python dependencies
RUN apt-get update && apt-get install -y \
  locales \
  python3 \
  python3-pip \
  pkg-config\
  curl 


RUN python3 -m pip install -U pip
RUN pip3 install -r requirements.txt

# Set the locale (required for uvicorn)
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
  dpkg-reconfigure --frontend=noninteractive locales && \
  update-locale LANG=en_US.UTF-8
ENV LANG en_US.UTF-8 

WORKDIR /main

CMD ["uvicorn", "start:app", "--host", "0.0.0.0", "--port", "4343"]



