FROM nvidia/cuda:10.0-base-ubuntu18.04

LABEL maintainer "NVIDIA CORPORATION <cudatools@nvidia.com>"


# The commands below install Cuda and libcudnn in order for the code to run on the GPU
ENV CUDNN_VERSION 7.4.2.24
LABEL com.nvidia.cudnn.version="${CUDNN_VERSION}"


RUN apt-get update && apt-get install -y --no-install-recommends \
  libcudnn7=$CUDNN_VERSION-1+cuda10.0 && \
  apt-mark hold libcudnn7 && \
  rm -rf /var/lib/apt/lists/*

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
	vim \
	nano \
        git \
        wget \
        ssh \
	cuda-command-line-tools-10-0 \
        cuda-cublas-10-0 \
        cuda-cufft-10-0 \
        cuda-curand-10-0 \
        cuda-cusolver-10-0 \
        cuda-cusparse-10-0 \
        libboost-all-dev \
        libgflags-dev \
        libgoogle-glog-dev \
        libhdf5-serial-dev \
        libleveldb-dev \
        liblmdb-dev \
        libopencv-dev \
        libprotobuf-dev \
        libsnappy-dev \
	liblapacke-dev \
	libatlas-base-dev \
	libatlas3-base \
        python3-dev \
        python3-numpy \
        python3-pip \
        python3-setuptools \
        python3-scipy \
	protobuf-compiler \	
	python3-tk && \
    	rm -rf /var/lib/apt/lists/*

RUN mkdir -p /tensorflow/models/research

WORKDIR /tensorflow/models/research

COPY ./research /tensorflow/models/research/

WORKDIR /

RUN pip3 install --upgrade pip

RUN pip3 install Cython jupyter matplotlib pillow lxml pandas contextlib2 cmake numpy==1.17.5
RUN pip3 install tensorflow-gpu==1.13.1

#RUN git clone https://github.com/cocodataset/cocoapi.git 

COPY cocoapi /cocoapi

WORKDIR /cocoapi/PythonAPI

RUN make 

RUN cp -r pycocotools /tensorflow/models/research/

WORKDIR /tensorflow/models/research/

#RUN ls

RUN protoc object_detection/protos/*.proto --python_out=.

#RUN pwd

RUN export PYTHONPATH=$PYTHONPATH:/tensorflow/models/research:tensorflow/models/research/slim


RUN apt-get update && apt-get install locales

RUN pip3 install fastapi[all]

# Set the locale (required for uvicorn)
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
  dpkg-reconfigure --frontend=noninteractive locales && \
  update-locale LANG=en_US.UTF-8
ENV LANG en_US.UTF-8 

#CMD "/data/prepare_data_docker.sh"

COPY ./networks_weights /weights

COPY ./weights_crawler.py /weights_crawler.py

RUN python3 /weights_crawler.py

WORKDIR /api

CMD uvicorn main:app --host 0.0.0.0  --port 5252
