FROM python:3.6

LABEL maintainer="joe.sleiman@bmw.de"

COPY docker/requirements.txt .

RUN pip install -r requirements.txt

WORKDIR /main
    
CMD ["uvicorn", "start:app", "--host", "0.0.0.0", "--port", "4343"]

